@Restaurants.API_HostAddress = https://localhost:7087

@id = 5
GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Mix Grill",
  "Description": "Shawerma",
  "Category": "Shawerma",
  "HasDelivery": true,
  "ContactEmail": "mixgrill900@gmail.com",
  "ContactNumber": "0598546723",
  "City": "Amman",
  "Street": "Queen Alia Street",
  "PostalCode": "15143"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###
GET https://localhost:7087/api/restaurants


###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json

{
  "Name": "Mix Grill",
  "Description": "Shawerma",
  "HasDelivery": true
}